version: "3.7"

services:
  php:
    container_name: ${ADGALR_COMPOSE_PROJECT_NAME}_php
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    build:
      context: .docker/php7.2-dev
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - .:/packages/Alerting:rw
    working_dir: /packages/Alerting
    environment:
      TRAVIS: ${TRAVIS:-0}
      TRAVIS_BUILD_NUMBER: ${TRAVIS_BUILD_NUMBER:-0}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID:-0}
